/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lobochu' at '4/10/16 9:43 AM' with Gradle 2.12
 *
 * @author lobochu, @date 4/10/16 9:43 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
